export enum EventCategory {
    CONFERENCE = 'CONFERENCE',
    WORKSHOP = 'WORKSHOP',
    SEMINAR = 'SEMINAR',
    FESTIVAL = 'FESTIVAL',
    CONCERT = 'CONCERT',
    EXHIBITION = 'EXHIBITION',
    SPORTS = 'SPORTS',
    CHARITY_GALA = 'CHARITY_GALA',
    COMMUNITY_MEETING = 'COMMUNITY_MEETING',
    EDUCATIONAL = 'EDUCATIONAL',
  }